/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GatedRouteImport } from './routes/_gated'
import { Route as GatedIndexRouteImport } from './routes/_gated.index'
import { Route as GatedManageRouteImport } from './routes/_gated.manage'
import { Route as GatedCalendarIndexRouteImport } from './routes/_gated.calendar.index'
import { Route as GatedCalendarCalendarKeyRouteImport } from './routes/_gated.calendar.$calendarKey'

const GatedRoute = GatedRouteImport.update({
  id: '/_gated',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedIndexRoute = GatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GatedRoute,
} as any)
const GatedManageRoute = GatedManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => GatedRoute,
} as any)
const GatedCalendarIndexRoute = GatedCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => GatedRoute,
} as any)
const GatedCalendarCalendarKeyRoute =
  GatedCalendarCalendarKeyRouteImport.update({
    id: '/calendar/$calendarKey',
    path: '/calendar/$calendarKey',
    getParentRoute: () => GatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof GatedIndexRoute
  '/manage': typeof GatedManageRoute
  '/calendar/$calendarKey': typeof GatedCalendarCalendarKeyRoute
  '/calendar/': typeof GatedCalendarIndexRoute
}
export interface FileRoutesByTo {
  '/manage': typeof GatedManageRoute
  '/': typeof GatedIndexRoute
  '/calendar/$calendarKey': typeof GatedCalendarCalendarKeyRoute
  '/calendar': typeof GatedCalendarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_gated': typeof GatedRouteWithChildren
  '/_gated/manage': typeof GatedManageRoute
  '/_gated/': typeof GatedIndexRoute
  '/_gated/calendar/$calendarKey': typeof GatedCalendarCalendarKeyRoute
  '/_gated/calendar/': typeof GatedCalendarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manage' | '/calendar/$calendarKey' | '/calendar/'
  fileRoutesByTo: FileRoutesByTo
  to: '/manage' | '/' | '/calendar/$calendarKey' | '/calendar'
  id:
    | '__root__'
    | '/_gated'
    | '/_gated/manage'
    | '/_gated/'
    | '/_gated/calendar/$calendarKey'
    | '/_gated/calendar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GatedRoute: typeof GatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_gated': {
      id: '/_gated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/': {
      id: '/_gated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GatedIndexRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/manage': {
      id: '/_gated/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof GatedManageRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/calendar/': {
      id: '/_gated/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof GatedCalendarIndexRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/calendar/$calendarKey': {
      id: '/_gated/calendar/$calendarKey'
      path: '/calendar/$calendarKey'
      fullPath: '/calendar/$calendarKey'
      preLoaderRoute: typeof GatedCalendarCalendarKeyRouteImport
      parentRoute: typeof GatedRoute
    }
  }
}

interface GatedRouteChildren {
  GatedManageRoute: typeof GatedManageRoute
  GatedIndexRoute: typeof GatedIndexRoute
  GatedCalendarCalendarKeyRoute: typeof GatedCalendarCalendarKeyRoute
  GatedCalendarIndexRoute: typeof GatedCalendarIndexRoute
}

const GatedRouteChildren: GatedRouteChildren = {
  GatedManageRoute: GatedManageRoute,
  GatedIndexRoute: GatedIndexRoute,
  GatedCalendarCalendarKeyRoute: GatedCalendarCalendarKeyRoute,
  GatedCalendarIndexRoute: GatedCalendarIndexRoute,
}

const GatedRouteWithChildren = GatedRoute._addFileChildren(GatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GatedRoute: GatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
